name: OPChat
version: 1.0
api-version: 1.15
description: OPChat
author: kubotan
website: https://gorogoro.space/
main: space.gorogoro.opchat.OPChat

commands:
  o:
    description: Operator's chat system.
    usage: /<command> <message>
