name: OPChat
version: '${version}'
api-version: '1.21.11'
description: OPChat
author: kubotan
website: https://www.gorogoro.space/
main: space.gorogoro.opchat.OPChat

commands:
  o:
    description: Operator's chat system.
    usage: /<command> <message>
  url:
    description: Post url
    usage: /<command> <message>
  opchatoff:
    description: OPチャットの ON / OFF を切り替えます(配信時など)
    usage: /<command>
